- name: Check if step binary exists
  stat:
    path: "/tmp/step_linux_{{ step_cli_version }}_{{ architecture }}.tar.gz"
  register: result

- name: Download step binary
  get_url:
    url: "https://github.com/smallstep/cli/releases/download/v{{ step_cli_version }}/step_linux_{{ step_cli_version }}_{{ architecture }}.tar.gz"
    dest: "/tmp/step_linux_{{ step_cli_version }}_{{ architecture }}.tar.gz"
    mode: '0755'
    timeout: 30
  when: not result.stat.exists

- name: Unarchive step binary
  unarchive:
    remote_src: yes
    src: /tmp/step_linux_{{ step_cli_version }}_{{ architecture }}.tar.gz
    dest: /tmp

- name: Link binaries to correct version
  copy:
    src: "/tmp/step_{{ step_cli_version }}/bin/step"
    remote_src: yes
    dest: "/usr/bin/step"
    mode: a+x